config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  resources :users, only: [:index, :show]
  root to: 'pages#home'
  get '/about/', to: 'pages#about'
  get '/terms/', to: 'pages#terms'
  get '/update/', to: 'pages#update'
  get '/s/:id' => 'shortener/shortened_urls#show'

  resources :areas do
    resources :sub_areas, only: [:new, :create, :edit, :update]
  end
  resources :sub_areas, only: [:show, :destroy] do
    resources :od_routes, only: [:new, :create, :edit, :update]
  end
  resources :od_routes, only: [:show, :destroy, :edit] do
    resources :od_logs, only: [:new, :create, :edit, :update]
    resources :od_route_reviews, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :od_logs, only: [:index, :destroy]

  resources :gyms do
    resources :routes, only: [:new, :create, :edit, :update]
  end
  resources :routes do
    resources :logs, only: [:new, :create, :edit, :update]
  end
  resources :routes, only: [:index, :show, :destroy]
  resources :logs, only: [:index, :destroy] do
    member do
      get 'duplicate'
    end
  end

end

app/models/od_route.rb
class OdRoute < ApplicationRecord
  belongs_to :grade
  belongs_to :sub_area
  belongs_to :category
  has_many :od_logs
  has_many :od_route_reviews
  has_one :area, through: :sub_area
  validates :route_name, presence: true, uniqueness: { scope: :sub_area,
    message: "同一サブエリア内に同じ名前の課題が存在します", case_sensitive: false }
  validates :route_name_katakana, presence: true, uniqueness: { scope: :sub_area,
    message: "同一サブエリア内に同じ名前の課題が存在します", case_sensitive: false }
  validates :category_id, presence: true
  validates :grade_id, presence: true
  validates :route_type, presence: true

  def combined_grade
    "#{Grade.find_by(id: grade_id).grade}#{SubGrade.find_by(id: sub_grade_id).sub_grade.to_s unless sub_grade_id.nil?}"
  end

  def latest_log_date
    od_logs.order(date: 'DESC').first.date
  end

  def best_status
    if od_logs.exists?
      Status.find_by(id: od_logs.order(status_id: 'ASC').first.status_id).status
    end
  end

end

app/controllers/od_routes_controller.rb
class OdRoutesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_od_route, only: [:show, :edit, :update, :destroy]

  def index
    @od_routes = policy_scope(OdRoute).all
  end

  def show
    @sub_area = @od_route.sub_area
    @area = @sub_area.area
    if user_signed_in?
      @od_logs = @od_route.od_logs.where('od_logs.user_id = ?', current_user.id)
      @od_route_reviews = @od_route.od_route_reviews.where('od_route_reviews.user_id = ? OR od_route_reviews.privacy_setting > ?', current_user.id, 0)
    else
      @od_logs = nil
      @od_route_reviews = @od_route.od_route_reviews.where('od_route_reviews.privacy_setting = ?', 2)
    end
  end

  def new
    @sub_area = SubArea.find(params[:sub_area_id])
    @grades = Grade.all
    @sub_grades = SubGrade.all
    @od_route = OdRoute.new
    authorize @od_route
  end

  def create
    @sub_area = SubArea.find(params[:sub_area_id])
    @od_route = OdRoute.new(od_route_params)
    authorize @od_route
    @od_route.sub_area = @sub_area
    if @od_route.grade_id < 20
      @od_route.grade_for_chart = 20 - (20 - @od_route.grade_id.to_f) * 0.25
    else
      if @od_route.sub_grade_id.nil?
          @od_route.grade_for_chart = @od_route.grade_id.to_f +0.375
      else
        @od_route.grade_for_chart = @od_route.grade_id.to_f + (@od_route.sub_grade_id.to_f - 2) * 0.125
      end
    end
    if @od_route.save
      redirect_to sub_area_path(@sub_area)
    else
      render :new
    end
  end

  def edit
    @sub_area = @od_route.sub_area
  end

  def update
    if @od_route.update(od_route_params)
      if @od_route.grade_id < 20
        @od_route.grade_for_chart = 20 - (20 - @od_route.grade_id.to_f) * 0.25
      else
        if @od_route.sub_grade_id.nil?
            @od_route.grade_for_chart = @od_route.grade_id.to_f +0.375
        else
          @od_route.grade_for_chart = @od_route.grade_id.to_f + (@od_route.sub_grade_id.to_f - 2) * 0.125
        end
      end
      @od_route.save
      redirect_to od_route_path(@od_route)
    else
      render :edit
    end
  end

  def destroy
    if @od_route.destroy
      redirect_to sub_area_path(@od_route.sub_area)
    else
      render :show
    end
  end

  private

  def set_od_route
    @od_route = OdRoute.find(params[:id])
    authorize @od_route
  end

  def od_route_params
    params.require(:od_route).permit(:route_name, :route_name_katakana, :route_name_alphabet, :grade_id, :sub_grade_id, :sub_area_id, :category_id, :route_type)
  end

end

app/views/od_routes/_form.html.erb
<div class="container mt-3  px-2">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h4><%= @sub_area.sub_area_name %></h4>
      <%= simple_form_for [@sub_area, @od_route] do |f| %>
        <%= f.input :route_name,
               label: false,
         placeholder: 'ルート名' %>
        <%= f.input :route_name_katakana,
               label: false,
         placeholder: 'ルート名(カタカナ)' %>
        <%= f.input :grade_id,
               label: false,
              prompt: 'グレードを選択',
          collection: Grade.all,
          label_method: :grade,
          value_method: :id %>
        <%= f.input :sub_grade_id,
               label: false,
              prompt: 'サブグレードを選択(任意)',
          collection: SubGrade.all,
          label_method: :sub_grade,
          value_method: :id %>
        <%= f.input :route_type,
               label: false,
              prompt: 'タイプを選択',
          collection: ['スラブ/緩傾斜壁', '垂壁', '前傾壁', '強傾斜壁', 'ルーフ'] %>
        <%= f.input :category_id,
               label: false,
              prompt: 'カテゴリーを選択',
          collection: Category.all,
          label_method: :category,
          value_method: :id %>
        <%= f.submit '登録', class:'btn btn-primary btn-lg btn-block mb-3' %>
      <% end %>
      <% unless @od_route.id.nil? %>
        <%= link_to '課題を削除', od_route_path(@od_route), method: :delete, data: {confirm: "課題を削除すると、この課題のログもすべて削除されます。本当に削除しますか?"}, class:'btn btn-outline-warning btn-lg btn-block mb-3' %>
      <% end %>
      <%= link_to '戻る', sub_area_path(@sub_area), class:'btn btn-outline-secondary btn-lg btn-block mb-3' %>
    </div>
  </div>
</div>

app/views/od_routes/index.html.erb
<h1>OdRoutes#index</h1>
<p>Find me in app/views/od_routes/index.html.erb</p>

app/views/od_routes/show.html.erb
<div class="container mt-3 px-2">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <div class="mb-2">
        <%= link_to 'エリア一覧', areas_path %> >
        <%= link_to area_path(@area) do %>
          <%= @area.area_name %>
        <% end %> >
        <%= link_to sub_area_path(@sub_area) do %>
          <%= @sub_area.sub_area_name %>
        <% end %>
      </div>
      <div>
        <span  style="font-size: 1.3em" >
          <%= @od_route.route_name %>
        </span>
          <%= @od_route.category.category %> <%= @od_route.combined_grade %>
        <% if user_signed_in? && current_user.admin? %>
          &nbsp;<%= link_to '編集', edit_od_route_path(@od_route) %>
        <% end %>
      </div>
      <div>
        <% if @od_route_reviews.exists? %>
          <% @od_route_reviews.each do |od_route_review| %>
            <div class="card my-2">
              <div class="d-flex align-items-center">
                <div>
                  <% if od_route_review.image.blank? %>
                    <%= image_tag 'no_image_logo.png', size:'100x100', class:'rounded mr-3' %>
                  <% else %>
                    <%= cl_image_tag od_route_review.image, height: 100, width: 100, crop: :fill, class:'rounded mr-3' %>
                  <% end %>
                </div>
                <div>
                  <div>
                    <% od_route_review.rating.times do %>
                      <i class="fas fa-star"></i>
                    <% end %>
                  </div>
                  <div>
                    <%= od_route_review.comment %>
                  </div>
                  <div>
                    by <%= od_route_review.user.nickname %>さん
                    <% if od_route_review.user == current_user %>
                      <%= link_to '編集', edit_od_route_od_route_review_path(@od_route, od_route_review) %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        <% if user_signed_in? && @od_route.od_route_reviews.where('od_route_reviews.user_id = ?', current_user.id).count == 0 %>
          <%= link_to 'レビューを書く', new_od_route_od_route_review_path(@od_route)  %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <div>
          <h5 class="mt-3">ログ</h5>
          <% if @od_logs.exists? %>
            <% @od_logs.order(date: 'DESC').each do |od_log| %>
              <div class="card p-1 my-1">

                  <div>
                    <%= link_to edit_od_route_od_log_path(od_log.od_route, od_log) do %>
                    <span style="font-size: 1.1rem"><%= od_log.date %></span>
                    <%= Status.find_by(id:od_log.status_id).status %>
                    <% end %>
                  </div>
                <div>
                  <%= od_log.comment %>
                </div>
                <div class="text-right">
                  <%= link_to od_log_path(od_log), method: :delete, data: {confirm: "本当に削除しますか?"} do %>
                    <i class="far fa-trash-alt"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% else %>
            ログがまだ登録されていません
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="container fixed-bottom">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <%= link_to 'ログを追加', new_od_route_od_log_path(@od_route), class:'btn btn-primary btn-block btn-lg my-3' %>
    </div>
  </div>
</div>