config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  resources :users, only: [:index, :show]
  root to: 'pages#home'
  get '/about/', to: 'pages#about'
  get '/terms/', to: 'pages#terms'
  get '/update/', to: 'pages#update'
  get '/s/:id' => 'shortener/shortened_urls#show'

  resources :areas do
    resources :sub_areas, only: [:new, :create, :edit, :update]
  end
  resources :sub_areas, only: [:show, :destroy] do
    resources :od_routes, only: [:new, :create, :edit, :update]
  end
  resources :od_routes, only: [:show, :destroy, :edit] do
    resources :od_logs, only: [:new, :create, :edit, :update]
    resources :od_route_reviews, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :od_logs, only: [:index, :destroy]

  resources :gyms do
    resources :routes, only: [:new, :create, :edit, :update]
  end
  resources :routes do
    resources :logs, only: [:new, :create, :edit, :update]
  end
  resources :routes, only: [:index, :show, :destroy]
  resources :logs, only: [:index, :destroy] do
    member do
      get 'duplicate'
    end
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <div><%= link_to 'ホーム', root_path %></div>
    <div><%= link_to '更新情報', update_path %></div>
    <div><%= link_to '運営者情報', about_path %></div>
    <div><%= link_to '利用規約', terms_path %></div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <h3 class="mb-0">クラログ</h3>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= active_link_to "ホーム", root_path, active: :exact, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "ジム検索/選択", gyms_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "岩場検索/選択", areas_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "ダッシュボード", "/users/#{current_user.hash_string}", class: "nav-link" %>
        </li>
        <li>
          <%= active_link_to "ランキング", users_path(from: Date.today.beginning_of_month, to: Date.today.end_of_month), active: :exact, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "アカウント設定", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete , class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= active_link_to "ホーム", root_path, active: :exact, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "ジム検索/選択", gyms_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "岩場検索/選択", areas_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "アカウント登録(無料)", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>