config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  resources :users, only: [:index, :show]
  root to: 'pages#home'
  get '/about/', to: 'pages#about'
  get '/terms/', to: 'pages#terms'
  get '/update/', to: 'pages#update'
  get '/s/:id' => 'shortener/shortened_urls#show'

  resources :areas do
    resources :sub_areas, only: [:new, :create, :edit, :update]
  end
  resources :sub_areas, only: [:show, :destroy] do
    resources :od_routes, only: [:new, :create, :edit, :update]
  end
  resources :od_routes, only: [:show, :destroy, :edit] do
    resources :od_logs, only: [:new, :create, :edit, :update]
    resources :od_route_reviews, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :od_logs, only: [:index, :destroy]

  resources :gyms do
    resources :routes, only: [:new, :create, :edit, :update]
  end
  resources :routes do
    resources :logs, only: [:new, :create, :edit, :update]
  end
  resources :routes, only: [:index, :show, :destroy]
  resources :logs, only: [:index, :destroy] do
    member do
      get 'duplicate'
    end
  end

end

app/models/sub_area.rb
class SubArea < ApplicationRecord
  belongs_to :area
  has_many :od_routes
  has_many :od_logs, through: :od_routes
  validates :sub_area_name, presence: true, uniqueness: { scope: :area,
    message: "同一エリア内に同じ名前のサブエリアが存在します", case_sensitive: false }
  validates :sub_area_name_katakana, presence: true, uniqueness: { scope: :area,
    message: "同一エリア内に同じ名前のサブエリアが存在します", case_sensitive: false }
end

app/controllers/sub_areas_controller.rb
class SubAreasController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_sub_area, only: [:show, :edit, :update, :destroy]

  def show
    @area = @sub_area.area
    @od_routes = @sub_area.od_routes.order(grade_id: 'ASC').order(sub_grade_id: 'ASC')
  end

  def new
    @area = Area.find(params[:area_id])
    @sub_area = SubArea.new
    authorize @sub_area
  end

  def create
    @area = Area.find(params[:area_id])
    @sub_area = SubArea.new(sub_area_params)
    authorize @sub_area
    @sub_area.area = @area
    if @sub_area.save
      redirect_to area_path(@area)
    else
      render :new
    end
  end

  def edit
    @area = @sub_area.area
  end

  def update

  end

  def destroy
    if @sub_area.destroy
      redirect_to area_path(@area)
    else
      render :edit
    end
  end

  private

  def set_sub_area
    @sub_area = SubArea.find(params[:id])
    authorize @sub_area
  end

  def sub_area_params
    params.require(:sub_area).permit(:sub_area_name, :sub_area_name_katakana, :sub_area_name_alphabet)
  end
end

app/views/sub_areas/_form.html.erb
<div class="container mt-3  px-2">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h4><%= link_to @area.area_name, area_path(@area) %></h4>
      <%= simple_form_for [@area, @sub_area] do |f| %>
        <%= f.input :sub_area_name,
               label: false,
         placeholder: 'サブエリア名' %>
        <%= f.input :sub_area_name_katakana,
               label: false,
         placeholder: 'サブエリア名(カタカナ)' %>
        <%= f.submit '登録', class:'btn btn-primary btn-block mb-3' %>
      <% end %>
      <% unless @sub_area.id.nil? %>
        <%= link_to 'サブエリアを削除', sub_area_path(@sub_area), method: :delete, data: {confirm: "本当に削除しますか?"}, class:'btn btn-outline-warning btn-lg btn-block mb-3' %>
      <% end %>
      <%= link_to '戻る', area_path(@area), class:'btn btn-outline-secondary btn-lg btn-block mb-3' %>
    </div>
  </div>
</div>

app/views/sub_areas/show.html.erb
<div class="container mt-3 px-2">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 mb-5 pb-3">
      <div class="d-flex align-items-center">
        <div class="mb-2">
          <%= link_to 'エリア一覧', areas_path %> >
          <%= link_to area_path(@area) do %>
            <%= @area.area_name %>
          <% end %> >
          <span  style="font-size: 1.2em" >
            <%= @sub_area.sub_area_name %>
          </span>
          <% if user_signed_in? && current_user.admin? %>
            &nbsp;<%= link_to '編集', edit_area_sub_area_path(@area, @sub_area) %>
          <% end %>
        </div>
      </div>
      <div>
        <% @od_routes.each do |od_route| %>
          <div class="card my-2 p-1 ">
            <%= link_to od_route_path(od_route) do %>
              <div>
                <span style="font-size: 1.2em"><%= od_route.route_name %></span> <%= od_route.combined_grade %>
              </div>
            <% end %>
            <div>
              <% if user_signed_in? && od_route.od_logs.where('od_logs.user_id = ?', current_user.id).exists? %>
                <%= od_route.od_logs.where('od_logs.user_id = ?', current_user.id).order(date: 'DESC').first.date  %>
                <%= Status.find_by(id: od_route.od_logs.where('od_logs.user_id = ?', current_user.id).order(status_id: 'ASC').first.status_id).status%>
                <%= od_route.od_logs.where('od_logs.user_id = ?', current_user.id).count %>トライ
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <%= link_to "新規ルート/課題登録", new_sub_area_od_route_path(@sub_area), class:"btn btn-outline-primary btn-block my-3" %>
    </div>
  </div>
</div>