config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  resources :users, only: [:index, :show]
  root to: 'pages#home'
  get '/about/', to: 'pages#about'
  get '/terms/', to: 'pages#terms'
  get '/update/', to: 'pages#update'
  get '/s/:id' => 'shortener/shortened_urls#show'

  resources :areas do
    resources :sub_areas, only: [:new, :create, :edit, :update]
  end
  resources :sub_areas, only: [:show, :destroy] do
    resources :od_routes, only: [:new, :create, :edit, :update]
  end
  resources :od_routes, only: [:show, :destroy, :edit] do
    resources :od_logs, only: [:new, :create, :edit, :update]
    resources :od_route_reviews, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :od_logs, only: [:index, :destroy]

  resources :gyms do
    resources :routes, only: [:new, :create, :edit, :update]
  end
  resources :routes do
    resources :logs, only: [:new, :create, :edit, :update]
  end
  resources :routes, only: [:index, :show, :destroy]
  resources :logs, only: [:index, :destroy] do
    member do
      get 'duplicate'
    end
  end

end

app/models/gym.rb
class Gym < ApplicationRecord
  mount_uploader :image, PhotoUploader
  has_many :routes
  has_many :logs, through: :routes
  has_many :users, through: :routes
  validates :name, presence: true, uniqueness: true
  validates :name_katakana, presence: true, uniqueness: true
  validates :name_alphabet, presence: true, uniqueness: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def last_visit_date(user)
    routes.where(user_id: user.id).joins(:logs).order(date: 'DESC').first.logs.order(date: 'DESC').first.date.to_date if routes.where(user_id: user.id).joins(:logs).exists?
  end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_gym, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR name_katakana ILIKE :query OR name_alphabet ILIKE :query OR address ILIKE :query"
      @gyms = policy_scope(Gym).all.where(sql_query, query:"%#{params[:query]}%").order(:name).page(params[:page]).per(10)
    else
      @gyms = policy_scope(Gym).order(:name).page(params[:page]).per(20)
    end

    if user_signed_in?
      @last_five_gyms_visited = current_user.logs.joins(:route).select('routes.gym_id').group('routes.gym_id').maximum('logs.date').sort_by{|gym_id, date| date}.reverse.first(5)
    end
 end

  def show
    @markers =
      [{
        lat: @gym.latitude,
        lng: @gym.longitude
      }]

    @from = params[:from].to_date unless params[:from].nil?
    @to = params[:to].to_date unless params[:to].nil?
    @routes = @gym.routes.where('routes.user_id = ?', current_user.id).order(grade_id: 'DESC').order(sub_grade_id: 'DESC').order(route_name: 'ASC')
    unless @from.nil? | @to.nil?
      @routes = @routes.joins(:logs).where('logs.date BETWEEN ? AND ?', @from, @to ).group('routes.id')
    else
      if @routes.first.nil?
        @from = Date.today
      elsif @routes.first.log_ids.empty?
        @from = Date.today
      else
        @from = Log.joins(:route).where('routes.user_id = ?', current_user.id).order(date: 'ASC').first.date
      end
      @to = Date.today
    end

    @logs = Log.all.joins(:route).where('logs.date BETWEEN ? AND ? AND routes.user_id = ? AND routes.gym_id  = ?', @from, @to, current_user.id, @gym.id)
    @boulder_best =  @logs.joins(:route).where('routes.category_id = ? and logs.status_id < ?', 1, 4).order(grade_id: 'DESC').order(sub_grade_id: 'DESC').order(date: 'DESC').first if @logs.exists?
    @lead_best =  @logs.joins(:route).where('routes.category_id = ? and logs.status_id < ?', 2, 4).order(grade_id: 'DESC').order(sub_grade_id: 'DESC').order(date: 'DESC').first if @logs.exists?
  end

  def new
    @gym = Gym.new
    authorize @gym
  end

  def create
    @gym = Gym.new(gym_params)
    authorize @gym
    if @gym.save
      redirect_to gym_path(@gym)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @gym.update(gym_params)
      redirect_to gym_path(@gym)
    else
      render :edit
    end
  end

  def destroy
    if @gym.destroy
      redirect_to gyms_path
    else
      render :edit
    end
  end

  private

  def set_gym
    @gym = Gym.find(params[:id])
    authorize @gym
  end

  def gym_params
    params.require(:gym).permit(:name, :name_katakana, :name_alphabet, :address, :latitude, :longitude)
  end
end

app/views/gyms/_form.html.erb
  <%= simple_form_for @gym do |f| %>
    <%= f.input :name, label: false, placeholder: 'ジム名' %>
    <%= f.input :name_katakana, label: false, placeholder: 'ジム名(カタカナ)' %>
    <%= f.input :name_alphabet, label: false, placeholder: 'ジム名(アルファベット)' %>
    <%= f.input :address, label: false, placeholder: '住所' %>
    <%= f.input :latitude, label: false, placeholder: '緯度' %>
    <%= f.input :longitude, label: false, placeholder: '経度' %>
    <%= f.submit '登録', class:'btn btn-primary btn-block' %>
  <% end %>

app/views/gyms/edit.html.erb
<div class="container mt-3 mb-5 text-center  px-2">
  <h3 class="mb-3">ジム情報変更</h3>
  <%= render 'form' %>
  <%= link_to '削除', gym_path(@gym), method: :delete, data: { confirm: '本当に削除してよいですか？' }, class:'btn btn-outline-danger btn-block mt-3' %>
</div>

app/views/gyms/index.html.erb
<div class="container mt-3 px-2">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h4>ジム検索/選択</h4>
      <% if user_signed_in? && current_user.logs.exists? %>
        <h5>最近訪問したジム</h5>
        <% @last_five_gyms_visited.each do |gym| %>
          <div>
            <% visited_gym = Gym.find(gym[0]) %>
            <% last_visit = visited_gym.last_visit_date(current_user).to_date %>
            <%= link_to gym_path(visited_gym) do %>
              <span style="font-size: 1.2em"><%=  visited_gym.name %></span> - <%= last_visit.strftime("%Y年%m月%d日(#{%w(日 月 火 水 木 金 土)[last_visit.wday]})") %>
            <% end %>
          </div>
        <% end %>
      <% end %>
      <%= form_tag gyms_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control mt-3",
          placeholder: "ジム名(漢字、カナ、アルファベット)や住所の一部を入力"
        %>
        <%= submit_tag "絞り込み検索", class: "btn btn-primary btn-block btn-lg mt-3 mb-3" %>
      <% end %>
        <% if @gyms.present? %>
          <% @gyms.each do |gym| %>
            <div>
              <%= link_to gym_path(gym) do %>
                <span style="font-size: 1.2em"><%= gym.name %></span>  - <%= gym.address[0,3] %>
              <% end %>
            </div>
          <% end %>
          <div class="my-3 mx-auto">
            <%= paginate @gyms %>
          </div>
        <% else %>
          <div>検索条件に合致するジムがみつかりませんでした。</div>
          <div>検索キーワードを変更しても見つからない場合は、該当のジム名をinfo@climbing-log.comまでEメールにてお知らせください。</div>
          <% if current_user.admin? %>
            <%= link_to "新規ジム登録(管理者用)", new_gym_path, class:"btn btn-outline-primary btn-block my-3" %>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/gyms/new.html.erb
<div class="container mt-3 mb-5 text-center px-2">
  <h1 class="mb-3">新規ジム情報登録</h1>
  <%= render 'form' %>
</div>

app/views/gyms/show.html.erb
<div class="container mt-3 px-2">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 mb-5 pb-3">
      <div class='d-flex align-items-center'>
        <h4><%= @gym.name %></h4>
        <% if current_user.admin %>
          <%= link_to '編集', edit_gym_path(@gym) %>
        <% end %>
      </div>

<!-- summary -->
      <div class="card px-2 py-1 mt-1">
        <div>最終訪問日：
          <%= @gym.last_visit_date(current_user) %>
        </div>
        <div>
          トライ本数： <%= @logs.count %>
        </div>
        <div>
          完登本数： <%= @logs.where('status_id < ?', 4).count %>
        </div>
        <div>ボルダー最高グレード：
          <% unless @boulder_best.nil? %>
            <%= link_to route_path(@boulder_best.route) do %>
              <%= "#{@boulder_best.route.combined_grade} (#{@boulder_best.route.logs.where('status_id < ?', 4).first.date})" unless @boulder_best.route.nil?  %>
            <% end %>
          <% end %>
          </div>
        <div class="mb-1">リード最高グレード：
          <% unless @lead_best.nil? %>
            <%= link_to route_path(@lead_best.route) do %>
              <%= "#{@lead_best.route.combined_grade} (#{@lead_best.route.logs.where('status_id < ?', 4).first.date})"%>
            <% end %>
          <% end %>
        </div>
      </div>

<!-- dates -->
      <div class="text-left mt-2 mb-1" style="font-size: 15px;">
        <%= @from.strftime("%Y年%m月%d日(#{%w(日 月 火 水 木 金 土)[@from.wday]})") %> 〜 <%= @to.strftime("%Y年%m月%d日(#{%w(日 月 火 水 木 金 土)[@to.wday]})")  %>
      </div>

<!-- Period selector  -->
      <div class="btn-group btn-group-toggle d-flex mb-2">
        <%= active_link_to '全期間', gym_path(@gym),  active: :exact, class:"btn btn-outline-primary btn-sm"  %>
        <%= active_link_to '今年', gym_path(@gym, from: Date.today.beginning_of_year, to: Date.today.end_of_year), active: :exact, class:"btn btn-outline-primary btn-sm" %>
        <%= active_link_to '今月', gym_path(@gym, from: Date.today.beginning_of_month, to: Date.today.end_of_month), active: :exact, class:"btn btn-outline-primary btn-sm"  %>
        <%= active_link_to '今週', gym_path(@gym, from: Date.today.beginning_of_week, to: Date.today.end_of_week), active: :exact, class:"btn btn-outline-primary btn-sm"  %>
        <%= active_link_to '今日', gym_path(@gym, from: Date.today, to: Date.today), active: :exact, class:"btn btn-outline-primary btn-sm"  %>
      </div>

<!-- Status selector -->
      <div class="btn-group btn-group-toggle d-flex mb-2" data-toggle="buttons">
        <label class="btn btn-outline-primary btn-sm active">
          <input type="radio" name="options" id="showAll" autocomplete="off" checked class="flex-fill"> All
        </label>
        <label class="btn btn-outline-primary btn-sm">
          <input type="radio" name="options" id="sentsOnly" autocomplete="off" class="flex-fill"> 完登分のみ
        </label>
        <label class="btn btn-outline-primary btn-sm">
          <input type="radio" name="options" id="unsentsOnly" autocomplete="off" class="flex-fill"> 未完登分のみ
        </label>
      </div>

<!-- Category selector -->
      <div class="btn-group btn-group-toggle d-flex mb-3" data-toggle="buttons">
        <label class="btn btn-outline-primary btn-sm active">
          <input type="radio" name="options" id="allCategory" autocomplete="off" checked class="flex-fill"> All
        </label>
        <label class="btn btn-outline-primary btn-sm">
          <input type="radio" name="options" id="boulderOnly" autocomplete="off" class="flex-fill"> ボルダー
        </label>
        <label class="btn btn-outline-primary btn-sm">
          <input type="radio" name="options" id="leadOnly" autocomplete="off" class="flex-fill"> リード
        </label>
        <label class="btn btn-outline-primary btn-sm">
          <input type="radio" name="options" id="topropeOnly" autocomplete="off" class="flex-fill"> トップロープ
        </label>
        <label class="btn btn-outline-primary btn-sm">
          <input type="radio" name="options" id="nagamonoOnly" autocomplete="off" class="flex-fill"> ナガモノ
        </label>
      </div>


<!-- Results -->
      <div>
        <% @routes.each do |route| %>
          <div class="<%= route.sent ? 'sent' : 'unsent' %>">
            <div class="card my-2 p-0 category<%= route.category_id %>" style="background-color: <%= route.sent ? 'rgba(200,247,225,0.2)' : 'rgba(230,126,34,0.1)' %>;">
              <div class="d-flex align-items-center">
                <div>
                  <% if route.image.blank? %>
                    <%= link_to edit_route_path(route) do %>
                      <%= image_tag 'no_image_logo.png', size:'100x100', class:'rounded mr-3' %>
                    <% end %>
                  <% else %>
                    <%= cl_image_tag route.image, height: 100, width: 100, crop: :fill, class:"rounded mr-3" %>
                  <% end %>
                </div>
                <div>
                  <div>
                    <%= link_to route_path(route) do %>
                      <span style="font-size: 1.1rem;">
                        <%= Category.find_by(id:route.category_id).category %>
                        <%= route.combined_grade %>
                      </span>
                      <%= route.route_type %> <%= route.route_name %>
                    <% end %>
                  </div>
                  <div><%= route.comment %></div>
                  <div><%= route.latest_log_date if route.logs.exists? %> <%= route.best_status %> <%= route.logs.count %>トライ</div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="container fixed-bottom">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <%= link_to '課題を追加', new_gym_route_path(@gym), class:'btn btn-primary btn-lg btn-block mb-3' %>
    </div>
  </div>
</div>

<script>
  const sents = document.querySelectorAll('.sent');
  const unsents = document.querySelectorAll('.unsent');
  const boulders = document.querySelectorAll('.category1');
  const leads = document.querySelectorAll('.category2');
  const topropes = document.querySelectorAll('.category3');
  const nagamonos = document.querySelectorAll('.category4');

  const showAll = document.getElementById('showAll');
  const sentsOnly = document.getElementById('sentsOnly');
  const unsentsOnly = document.getElementById('unsentsOnly');

  const allCategory = document.getElementById('allCategory');
  const boulderOnly = document.getElementById('boulderOnly');
  const leadOnly = document.getElementById('leadOnly');
  const topropeOnly = document.getElementById('topropeOnly');
  const nagamonoOnly = document.getElementById('nagamonoOnly');

  showAll.addEventListener('focus',(event) => {
    sents.forEach((sent) => {
      sent.classList.remove('d-none');
    });
    unsents.forEach((unsent) => {
      unsent.classList.remove('d-none');
    });
  });
  sentsOnly.addEventListener('focus',(event) => {
    sents.forEach((sent) => {
      sent.classList.remove('d-none');
    });
  unsents.forEach((unsent) => {
      unsent.classList.add('d-none');
    });
  });
  unsentsOnly.addEventListener('focus',(event) => {
    sents.forEach((sent) => {
      sent.classList.add('d-none');
    });
  unsents.forEach((unsent) => {
      unsent.classList.remove('d-none');
    });
  });

  allCategory.addEventListener('focus',(event) => {
    boulders.forEach((boulder) => {
      boulder.classList.remove('d-none');
    });
    leads.forEach((lead) => {
      lead.classList.remove('d-none');
    });
    topropes.forEach((toprope) => {
      toprope.classList.remove('d-none');
    });
    nagamonos.forEach((nagamono) => {
      nagamono.classList.remove('d-none');
    });
  });

  boulderOnly.addEventListener('focus',(event) => {
    boulders.forEach((boulder) => {
      boulder.classList.remove('d-none');
    });
    leads.forEach((lead) => {
      lead.classList.add('d-none');
    });
    topropes.forEach((toprope) => {
      toprope.classList.add('d-none');
    });
    nagamonos.forEach((nagamono) => {
      nagamono.classList.add('d-none');
    });
  });

  leadOnly.addEventListener('focus',(event) => {
    boulders.forEach((boulder) => {
      boulder.classList.add('d-none');
    });
    leads.forEach((lead) => {
      lead.classList.remove('d-none');
    });
    topropes.forEach((toprope) => {
      toprope.classList.add('d-none');
    });
    nagamonos.forEach((nagamono) => {
      nagamono.classList.add('d-none');
    });
  });

  topropeOnly.addEventListener('focus',(event) => {
    boulders.forEach((boulder) => {
      boulder.classList.add('d-none');
    });
    leads.forEach((lead) => {
      lead.classList.add('d-none');
    });
    topropes.forEach((toprope) => {
      toprope.classList.remove('d-none');
    });
    nagamonos.forEach((nagamono) => {
      nagamono.classList.add('d-none');
    });
  });

  nagamonoOnly.addEventListener('focus',(event) => {
    boulders.forEach((boulder) => {
      boulder.classList.add('d-none');
    });
    leads.forEach((lead) => {
      lead.classList.add('d-none');
    });
    topropes.forEach((toprope) => {
      toprope.classList.add('d-none');
    });
    nagamonos.forEach((nagamono) => {
      nagamono.classList.remove('d-none');
    });
  });


</script>